CREATE DATABASE IF NOT EXISTS reservas_db;
USE reservas_db;

CREATE TABLE IF NOT EXISTS Usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Recursos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  tipo VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha DATETIME NOT NULL,
  UsuarioId INT NOT NULL,
  RecursoId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UsuarioId) REFERENCES Usuarios(id) ON DELETE CASCADE,
  FOREIGN KEY (RecursoId) REFERENCES Recursos(id) ON DELETE CASCADE
);

INSERT INTO Usuarios (nombre, email) VALUES
("Julio", "julio@test.com"),
("Ana", "ana@test.com");

INSERT INTO Recursos (nombre, tipo) VALUES
("Sala A", "Sala"),
("Sala B", "Sala"),
("Computadora 1", "PC");

INSERT INTO Reservas (fecha, UsuarioId, RecursoId) VALUES
("2026-03-06 10:00:00", 1, 1),
("2026-03-07 15:00:00", 2, 2);